repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.3"
    hooks:
      - id: vulture

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  - repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.245'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]

      - id: docformatter
        name: docformatter
        description: "Formats docstrings to follow PEP 257."
        entry: docformatter
        args: [-i]
        language: python
        types: [python]

      - id: bandit
        name: bandit
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: bandit
        language: python
        language_version: python3
        types: [python]

      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]

    # - id: flake8
    #   name: flake8
    #   stages: [commit]
    #   language: system
    #   entry: flake8
    #   types: [python]
    #   exclude: setup.py

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.7.0
    hooks:
      - id: nbqa-isort
        additional_dependencies: [isort==5.7.0]
        args: [--nbqa-mutate]
      - id: nbqa-black
        additional_dependencies: [black==20.8b1]
        args: [--nbqa-mutate]
      - id: nbqa-ruff
        name: nbqa-ruff
        description: Run 'ruff' on a Jupyter Notebook
        entry: nbqa ruff
        language: python
        additional_dependencies: [ruff]
        require_serial: true
        types_or: [jupyter, markdown]
      - id: nbqa-mypy
        name: nbqa-mypy
        description: Run 'mypy' on a Jupyter Notebook
        entry: nbqa mypy
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [mypy]
            