[tool.poetry]
name = "{{cookiecutter.directory_name}}"
version = "0.1.0"
description = ""
authors = ["{{cookiecutter.author_name}}"]

[tool.poetry.dependencies]
python = "^3.8"
typeguard = "^2.13.3"


[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"

###############################################################################
#
#                                 TESTS
#
###############################################################################
pytest = { version = "^7.2.0", optional = true}
pytest-cov = { version = "^4.0.0", optional = true}
pytest-xdist = { version = "^3.0", optional = true}
pytest-randomly = "^3.5.0"

###############################################################################
#
#                                 FIXERS
#
###############################################################################
black = { version = "^22.3.0", optional = true }
autoflake = { version = "^1.7.7", optional = true }
isort = { version = "^5.10.1", optional = true }
docformatter = { version = "^1.5.0", optional = true, extras=["tomli"] }
vulture = ">=1.0"


###############################################################################
#
#                                 LINTERS
#
###############################################################################
mypy = "^0.942"
interrogate = { version = "^1.5.0", optional = true }
flake8 = "^4.0.1"
bandit = "^1.7.0"
talisman = "^0.1.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build   
)/ 
'''