repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ""
    hooks:
      - id: mypy

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.245"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=90]

  - repo: https://github.com/PyCQA/docformatter
      rev: v1.7.1
      hooks:
        - id: docformatter
          additional_dependencies: [tomli]
          args: [--in-place, --config, ./pyproject.toml]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.7.0
    hooks:
      - id: nbqa-isort
        additional_dependencies: [isort==5.7.0]
        args: [--nbqa-mutate]
      - id: nbqa-black
        additional_dependencies: [black==20.8b1]
        args: [--nbqa-mutate]
      - id: nbqa-ruff
        name: nbqa-ruff
        description: Run 'ruff' on a Jupyter Notebook
        entry: nbqa ruff
        language: python
        additional_dependencies: [ruff]
        require_serial: true
        types_or: [jupyter, markdown]
      - id: nbqa-mypy
        name: nbqa-mypy
        description: Run 'mypy' on a Jupyter Notebook
        entry: nbqa mypy
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [mypy]
