repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1"
    hooks:
      - id: mypy

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ["-c", "./pyproject.toml", "-i", "-v"]
        pass_filenames: false
  
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: ["--in-place", "--config", "./pyproject.toml"]

  - repo: https://github.com/codespell-project/codespell
      rev: v2.2.5
      hooks:
        - id: codespell

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.7.0
    hooks:
      - id: nbqa-mypy

  - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.13.0
      hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
